SERVER_NAME = server
CLIENT_NAME = client
SERVER_BONUS_NAME = server_bonus
CLIENT_BONUS_NAME = client_bonus
CC = cc
CFLAGS = -Wall -Wextra -Werror
LDFLAGS = -L$(LIBFT_DIR) -lft
LIBFT_DIR = libft
LIBFT_LIB = $(LIBFT_DIR)/libft.a

MINITALK_DIR = mandatory

HEADER_DIR = $(MINITALK_DIR)/inc
HEADER = $(HEADER_DIR)/minitalk.h
INCLUDES = -I$(HEADER_DIR) -I$(LIBFT_DIR)

SRC_DIR = $(MINITALK_DIR)/src

SERVER_DIR = $(SRC_DIR)
SERVER_FILES = server.c
SERVER_SRCS = $(addprefix $(SERVER_DIR)/, $(SERVER_FILES))

CLIENT_DIR = $(SRC_DIR)
CLIENT_FILES = client.c
CLIENT_SRCS = $(addprefix $(CLIENT_DIR)/, $(CLIENT_FILES))

OBJS_DIR = $(MINITALK_DIR)/objs
SERVER_OBJS = $(addprefix $(OBJS_DIR)/, $(SERVER_FILES:.c=.o))
CLIENT_OBJS = $(addprefix $(OBJS_DIR)/, $(CLIENT_FILES:.c=.o))

MINITALK_BONUS_DIR = bonus

HEADER_BONUS_DIR = $(MINITALK_BONUS_DIR)/inc
HEADER_BONUS = $(HEADER_BONUS_DIR)/minitalk_bonus.h
INCLUDES_BONUS = -I$(HEADER_BONUS_DIR) -I$(LIBFT_DIR)

SRC_BONUS_DIR = $(MINITALK_BONUS_DIR)/src

SERVER_BONUS_DIR = $(SRC_BONUS_DIR)
SERVER_BONUS_FILES = server_bonus.c
SERVER_BONUS_SRCS = $(addprefix $(SERVER_BONUS_DIR)/, $(SERVER_BONUS_FILES))

CLIENT_BONUS_DIR = $(SRC_BONUS_DIR)
CLIENT_BONUS_FILES = client_bonus.c
CLIENT_BONUS_SRCS = $(addprefix $(CLIENT_BONUS_DIR)/, $(CLIENT_BONUS_FILES))

OBJS_BONUS_DIR = $(MINITALK_BONUS_DIR)/objs
SERVER_BONUS_OBJS = $(addprefix $(OBJS_BONUS_DIR)/, $(SERVER_BONUS_FILES:.c=.o))
CLIENT_BONUS_OBJS = $(addprefix $(OBJS_BONUS_DIR)/, $(CLIENT_BONUS_FILES:.c=.o))

all: $(SERVER_NAME) $(CLIENT_NAME)

bonus: $(SERVER_BONUS_NAME) $(CLIENT_BONUS_NAME)

clean:
	rm -rf $(SERVER_OBJS) $(CLIENT_OBJS) $(SERVER_BONUS_OBJS) $(CLIENT_BONUS_OBJS) $(OBJS_DIR) $(OBJS_BONUS_DIR)
	@make clean -C $(LIBFT_DIR)

fclean: clean
	rm -rf $(SERVER_NAME) $(CLIENT_NAME) $(SERVER_BONUS_NAME) $(CLIENT_BONUS_NAME)  $(LIBFT_LIB)

re: fclean all

$(SERVER_NAME): $(LIBFT_LIB) $(SERVER_OBJS)
	$(CC) $(CFLAGS) $(SERVER_OBJS) $(LDFLAGS) -o $(SERVER_NAME)

$(CLIENT_NAME): $(LIBFT_LIB) $(CLIENT_OBJS)
	$(CC) $(CFLAGS) $(CLIENT_OBJS) $(LDFLAGS) -o $(CLIENT_NAME)

$(SERVER_BONUS_NAME): $(LIBFT_LIB) $(SERVER_BONUS_OBJS)
	$(CC) $(CFLAGS) $(SERVER_BONUS_OBJS) $(LDFLAGS) -o $(SERVER_BONUS_NAME)

$(CLIENT_BONUS_NAME): $(LIBFT_LIB) $(CLIENT_BONUS_OBJS)
	$(CC) $(CFLAGS) $(CLIENT_BONUS_OBJS) $(LDFLAGS) -o $(CLIENT_BONUS_NAME)

$(LIBFT_LIB):
	@make -C $(LIBFT_DIR)

$(OBJS_DIR):
	mkdir -p $(OBJS_DIR)

$(OBJS_BONUS_DIR):
	mkdir -p $(OBJS_BONUS_DIR)

$(OBJS_DIR)/%.o: $(SERVER_DIR)/%.c $(HEADER) | $(OBJS_DIR)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(OBJS_DIR)/%.o: $(CLIENT_DIR)/%.c $(HEADER) | $(OBJS_DIR)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(OBJS_BONUS_DIR)/%.o: $(SERVER_BONUS_DIR)/%.c $(HEADER_BONUS) | $(OBJS_BONUS_DIR)
	$(CC) $(CFLAGS) $(INCLUDES_BONUS) -c $< -o $@

$(OBJS_BONUS_DIR)/%.o: $(CLIENT_BONUS_DIR)/%.c $(HEADER_BONUS) | $(OBJS_BONUS_DIR)
	$(CC) $(CFLAGS) $(INCLUDES_BONUS) -c $< -o $@

.PHONY: all clean fclean re
